[phases.setup]
nixPkgs = [
  "nodejs",
  "nodePackages.npm"
]

[phases.install]
cmds = [
  "npm install"
]

[phases.build]
cmds = [
  "npm run build"
]

[start]
cmd = "npm run preview -- --host 0.0.0.0 --port ${PORT:-8080}"
