[phases.setup]
nixPkgs = [
  "php82",
  "php82Packages.composer",
  "php82Packages.mbstring",
  "php82Packages.zip",
  "php82Packages.xml",
  "php82Packages.pdo_mysql"
]

[phases.install]
cmds = [
  "composer install --no-interaction --prefer-dist --optimize-autoloader"
]

[phases.build]
cmds = [
  "php artisan config:cache",
  "php artisan route:cache",
  "php artisan view:cache",
  "php artisan migrate:fresh --seed --force"
]

[start]
cmd = "php artisan serve --host=0.0.0.0 --port=${PORT:-8080}"
